spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/{role}/user/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/{role}/hubs/**
            - Path=/api/{role}/hub-routes/**
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 19091

jwt:
  secret:
    key: 09f001b9896c05dc6d2c353da804aa7e5d14622943889409dce157a8793af945067b8f07570c97529e1bed70ee339398c3fb576ba4547e2162ab9ea9aa365483

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/