server:
  port: 19100

spring:
  application:
    name: slack-service

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# swagger
springdoc:
  swagger-ui:
    path: /api-test
    groups-order: asc
  paths-to-match: /api/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/