spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
    refresh:
      enabled: true

# swagger
springdoc:
  swagger-ui:
    path: /api-test
    groups-order: asc
  paths-to-match: /api/**