server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
      discovery:
        enabled: false
      uri: http://localhost:8888
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/